export const COMMANDS: string[] = [
    "connect",
    "join",
    "enter",
    "rejoin",
    "desync",
    "feed",
    "plasmafor",
    "setplasmafarm",
    "exit",
    "chat",
    "emote",
    "net",
    "rename",
    "test",
    "split",
    "setemloop",
    "setmassthreshold",
    "setmassad",
    "setautorespawn",
    "setlvlmeta",
    "clear",
    // "setplasmameta",
    "setexecbreak",
    "hexsearch",
];
